### ISSUE TITLE
Hi; Please consider suppressing credentials output in: Manage Docker registry login credentials

### ISSUE THREAD

**Issue by prashantsomashekar** [nickjj/ansible-docker#114]
Hi.

Please consider suppressing the output for:
'Manage Docker registry login credentials'

This prints the password for the user to STDOUT.

Thank you.

**Comment by nickjj** [comment]
Hi,

Were you thinking of doing this with `no_log: True` on that task?

**Comment by prashantsomashekar** [comment]
Yup.

**Comment by nickjj** [comment]
I just pushed https://github.com/nickjj/ansible-docker/commit/af3e986e3dc1956f1f48ff82f6bc686ff1b8ed78 to the master branch which addresses this issue.

I ended up not using `no_log: true`. Instead it uses the `loop_control.label` feature which lets us customize what gets output. I chose to output the registry_url, username and the state which I think is enough information to see if Ansible logged you into the correct registry based on your inventory configuration.

Thanks a lot for opening this issue as it improved the security of the role!

**Comment by prashantsomashekar** [comment]
no_log suppresses all output (even with verbose).

"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",

**Comment by nickjj** [comment]
> no_log suppresses all output (even with verbose).

Yep but you can  set `ANSIBLE_DEBUG=1` and then `no_log: true` won't hide the output. It's the same idea that if a user can run ansible with `-v` then they can run ansible with `ANSIBLE_DEBUG=1` to bypass `no_log`.

Did you mainly want to hide the output during CI logs? If so I much prefer the label approach because you get the extra detail of what registry is being logged into. This is also nice for standard usage on your Ansible controller no matter where it runs.

**Comment by prashantsomashekar** [comment]
Hi.  Just general hiding, but ya, it is nice to see what is occurring without resorting to extra flags at runtime, etc.

Thank you for the support.
