### ISSUE TITLE
Galaxy version outdated

### ISSUE THREAD

**Issue by ngrie** [nickjj/ansible-docker#34]
It took me about an hour to find out why my `group_vars` are getting ignored ... the most recent commit where `docker_users` got `docker__users` did not find its way to ansible galaxy yet.

**Comment by nickjj** [comment]
Yikes, sorry about that. I didn't release it to the Galaxy yet because I had planned to make a few other changes before pushing a release.

I just created and pushed `v1.3.0` to the Galaxy which has the `__` variable style change. It also exposes a new variable where you can configure the Docker Compose download URL.

It sounds I need to come up with a README strategy that allows me to iterate on the role without pushing releases. Maybe a 1 liner at the top of the README that mentions this documentation is based on the master branch, and if you want to read the latest stable release, then click here -- and then the link would lead to the README for the latest stable release. I'll have to think about that.

**Comment by tjcim** [comment]
This caught me as well.
