### ISSUE TITLE
Support Centos 7/8

### ISSUE THREAD

**Issue by Serienmorder** [nickjj/ansible-docker#86]
Currently the role doesn't have support for Centos 7/8

Would it be possible for you to add this functionality?

**Comment by nickjj** [comment]
Hi,

This sort of goes back to PR https://github.com/nickjj/ansible-docker/pull/51 where some folks requested Feroda and CentOS support. It has some discussion on why it's not supported.

The TL;DR is it's because I do not run these distros in production and I wouldn't be comfortable adding official support for them.
