### ISSUE TITLE
Ubuntu 16.04 support

### ISSUE THREAD

**Issue by heiderich** [nickjj/ansible-docker#95]
In ff012c5bd853790073697e86f70859edfd9215e5 support for Ubuntu 16.04 was removed. The commit message says "It's been EOL since April 25th 2019". Where does this date come from? According to https://wiki.ubuntu.com/Releases

- the End of Life of Ubuntu 16.04 is April 2024, while
- the End of Standard Support for Ubuntu 14.04 was April 2019.

Are there actual incompatibilities with Ubuntu 16.04?

**Comment by nickjj** [comment]
Just doing some house keeping of issues / PRs and I'm closing this one.

Mainly because 16.04 is going to be end of EOL in April 2021. There's extended maintenance until 2024 but that's a premium offering from Ubuntu. I can't afford to maintain a distro beyond its normal EOL schedule.

Plus Docker Compose only supports Python 3.6+ at the moment and Ubuntu 16.04 has Python 3.5 by default which means it'll be quite some effort to get everything set up on Ubuntu 16.04.
